#!/bin/bash
mask=$1
output_name=$2

feat_dirs='/misc/purcell/alfonso/sternberg_cpac/sub-00373/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04001/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04004/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04005/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04009/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04013/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04015/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04018/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04027/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04028/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04164/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04165/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04169/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04170/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04171/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04173/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04178/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04181/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04201/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04204/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04209/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04210/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04211/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04215/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04216/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04217/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04221/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-04245/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-26896/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-27869/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-27872/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-27934/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-27960/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-27974/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-28620/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-28982/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-29073/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-29096/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-29332/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-31231/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-31323/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-31730/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-32159/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-32231/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-32310/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-32436/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-32756/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-32907/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-34273/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-34359/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-34437/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-34548/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-34736/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-34826/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-34926/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-35232/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-35272/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-35353/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-35557/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-36207/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-36487/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-36737/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-36866/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-36966/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-37117/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-37130/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-37149/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-37289/sternberg.feat
/misc/purcell/alfonso/sternberg_cpac/sub-37348/sternberg.feat'



/home/inb/lconcha/fmrilab_software/fsl_5.0.9/bin/featquery 69 $feat_dirs 1  stats/cope2 $output_name -p -s  $mask
sleep 5m
